# Docker and Docker Compose based environment for Drupal.
# Combines with docker-compose.common.yml
# See https://github.com/blinkreaction/docker-fig-drupal for more information and documentation.

# Web node
version: "2"

